ERP/Areas/Admin/Controllers/BaseController.cs
using Business.Interface;
using DocumentFormat.OpenXml.Spreadsheet;
using DocumentFormat.OpenXml.Vml;
using ERP.Controllers;
using ERP.Extensions;
using ERP.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;

namespace ERP.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BaseController : SettingsController
    {
        private static HttpContext Current => new HttpContextAccessor().HttpContext;
        private static ISuperAdminService _admin => (ISuperAdminService)Current.RequestServices.GetService(typeof(ISuperAdminService));

        public IActionResult GetState(int countryId)
        {
            try
            {
                var states = SuperCompanyDropdownBinder.State(countryId);

                return Json(new { status = true, data = states });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                return Json(new { status = false, message = MessageHelper.Error });
            }
        }
        public IActionResult GetDistrict(int stateId)
        {
            try
            {
                var states = SuperCompanyDropdownBinder.District(stateId);

                return Json(new { status = true, data = states });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                return Json(new { status = false, message = MessageHelper.Error });
            }
        }
        public IActionResult GetCity(int stateId)
        {
            try
            {
                var states = SuperCompanyDropdownBinder.City(stateId);

                return Json(new { status = true, data = states });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                return Json(new { status = false, message = MessageHelper.Error });
            }
        }
        public IActionResult GetTaluka(int districtID)
        {
            try
            {
                var states = SuperCompanyDropdownBinder.Taluka(districtID);

                return Json(new { status = true, data = states });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                return Json(new { status = false, message = MessageHelper.Error });
            }
        }
        public IActionResult GetZipcode(string q)
        {
            try
            {
                var zipcode = _admin.GetAllZipcodeAutoCompletAsync(q).Result;
                //var customers = (from a in zipcode select new 
                //                                        {
                //                label = customer.ContactName,
                //                val = customer.CustomerID
                //           }).ToList();
                return Json(zipcode);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                return Json(new { status = false, message = MessageHelper.Error });
            }
        }
    }
}

ERP/Areas/SuperAdmin/Controllers/ZipcodeController.cs
using Business.Entities;
using Business.Interface;
using Business.SQL;
using ERP.Controllers;
using ERP.Extensions;
using ERP.Helpers;
using GridCore.Server;
using GridShared;
using GridShared.Sorting;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel;
using System.Threading.Tasks;
namespace ERP.Areas.SuperAdmin.Controllers
{
    [Area("SuperAdmin"), Authorize]
    [DisplayName("Zipcode")]
    public class ZipcodeController : BaseController
    {
        private readonly ISuperAdminService _superAdmin;

        public ZipcodeController(ISuperAdminService superAdmin)
        {
            this._superAdmin = superAdmin;
        }

        public async Task<IActionResult> Index([FromQuery(Name = "grid-page")] string gridpage = "1", [FromQuery(Name = "grid-column")] string orderby = "", [FromQuery(Name = "grid-dir")] string sortby = "0", [FromQuery(Name = "grid-filter")] string gridfilter = "", [FromQuery(Name = "grid-search")] string search = "")
        {
            try
            {
                IQueryCollection query = Request.Query;

                Action<IGridColumnCollection<ZipcodeMasterMetadata>> columns = c =>
                {
                    c.Add(o => o.ZIPCode)
                      .Titled("Zipcode Name")
                      .SortInitialDirection(GridSortDirection.Ascending)
                      .SetWidth(110);
                    c.Add(o => o.AreaOfficeName)
                      .Titled("Area Name")
                      .SetWidth(110);

                    c.Add(o => o.TalukaName)
                      .Titled("Taluka Name")
                      .SetWidth(110);

                    c.Add(o => o.DistrictName)
                       .Titled("District Name")
                       .SetWidth(110);
                    c.Add(o => o.StateName)
                        .Titled("State Name")
                        .SetWidth(110);

                    c.Add(o => o.CountryName)
                        .Titled("Country Name")
                        .SetWidth(110);
                    c.Add(o => o.CountryShortName)
                           .Titled("Country Short Name")
                           .SetWidth(110);
                    c.Add()
                        .Encoded(false)
                        .Sanitized(false)
                        .SetWidth(60)
                     .RenderValueAs(o => $"<a class='btn' onclick = 'fnZipcode(this)' href = 'javascript:void(0)' data-id='{o.TalukaID}'  data-bs-toggle='offcanvas' data-bs-target='#canvas_zipcode' aria-controls='canvas_zipcode'><i class='bx bx-edit'></i></a>");
                };
                PagedDataTable<ZipcodeMasterMetadata> pds =await _superAdmin.GetAllZipcodeAsync(gridpage.ToInt(), PAGESIZE, search, orderby.RemoveSpace(), sortby == "0" ? "ASC" : "DESC");
                var server = new GridCoreServer<ZipcodeMasterMetadata>(pds, query, false, "ordersGrid",
                    columns, PAGESIZE, pds.TotalItemCount)
                    .Sortable()
                    .Searchable(true, false)
                    .ClearFiltersButton(false)
                    .SetStriped(true)
                    .ChangePageSize(true)
                    .WithGridItemsCount()
                    .WithPaging(PAGESIZE, pds.TotalItemCount)
                    .ChangeSkip(false)
                    .EmptyText("No record found")
                    ;
                return View(server.Grid);
            }
            catch
            {
                throw;
            }
        }

        [HttpPost]
        public async Task<PartialViewResult> Get(int id)
        {

            try
            {
                ZipcodeMasterMetadata model = await _superAdmin.GetZipcodeAsync(id);
                if (model == null)
                    model = new ZipcodeMasterMetadata();
                return PartialView("_add", model);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Save(ZipcodeMasterMetadata model)
        {
            try
            {
                int result = await _superAdmin.InsertOrUpdateZipcodeAsync(model);
                if (result > 0)
                {
                    if (model.StateID == 0)
                        return Json(new { status = true, message = MessageHelper.Added });
                    else
                        return Json(new { status = true, message = MessageHelper.Updated });
                }
                return Json(new { status = false, message = MessageHelper.Error });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                return Json(new { status = false, message = MessageHelper.Error });
            }
        }

       
    }
}

ERP/Areas/SuperAdmin/Views/Zipcode/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using Business.SQL
@using GridCore
@addTagHelper *, GridMvc

@model ISGrid
@{
    ViewData["Title"] = "Zipcode";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";

}
<div class="page-breadcrumb d-none d-sm-flex align-items-center pb-2 border-bottom">
    <div class="ps-3 col-md-6">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 p-0">
                <li class="breadcrumb-item">
                    <a asp-controller="Home" asp-action="Index" asp-area="SuperAdmin"><i class="bx bx-home-alt"></i></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Zipcode</li>
            </ol>
        </nav>
    </div>
    <div class="col-md-6 text-align-right">
        <a class="btn btn-primary px-5" onclick="fnZipcode(this)"
           href="javascript:void(0)"
           data-id="0"
           data-bs-toggle="offcanvas"
           data-bs-target="#canvas_zipcode"
           aria-controls="canvas_zipcode">
            Add Zipcode
        </a>
    </div>
</div>
<div class="row pt-2">
    <div class="col-md-12">
        <grid model="@Model" />
    </div>
</div>
<div class="offcanvas offcanvas-end" tabindex="-1" id="canvas_zipcode">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title">Zipcode</h5>
        <button type="button" class="btn-close te  xt-reset" data-bs-dismiss="offcanvas" aria-l abel="Close"></button>
    </div>
    <div class="offcanvas-body pt-3 pb-5">
        <div id="dvInfo">
        </div>
    </div>
</div>
<script type="text/javascript">
    var urladd = '@Url.Action("Get", "Zipcode")';
    function fnZipcode(obj) {
        var _id = $(obj).data('id');
        var _parameters = { id: _id };
       
        $.ajax({
            url: urladd,
            type: "POST",
            data: _parameters,
            success: function (data, textStatus, jqXHR) {
                $('#dvInfo').html(data);
                $("#canvas_zipcode").show();//('hide');
            }
        });
    }   
</script>
    

ERP/Areas/SuperAdmin/Views/Zipcode/_add.cshtml
@model ZipcodeMasterMetadata
<form method="post" id="frmzipcode" asp-area="SuperAdmin" class="row g-3 needs-validation" novalidate>
    <div class="row mt-3">
        <div class="col-md-12">

            <input type="hidden" asp-for="ZIPCodeID" />

            <div class="row mb-3">
                <label for="" class="col-sm-4 col-form-label text-end">Country<span class="required">*</span></label>
                <div class="col-sm-8">
                    <select class="form-select" asp-for="CountryID" asp-items="@SuperCompanyDropdownBinder.Countries()">
                        <option value="">--Select--</option>
                    </select>
                    <span asp-validation-for="CountryID" class="text-danger"></span>
                </div>
            </div>
            <div class="row mb-3">
                <label for="" class="col-sm-4 col-form-label text-end">State<span class="required">*</span></label>
                <div class="col-sm-8">
                    <select class="form-select" asp-for="StateID" asp-items="@SuperCompanyDropdownBinder.State(Model.CountryID)">
                        <option value="">--Select--</option>
                    </select>
                    <span asp-validation-for="StateID" class="text-danger"></span>
                </div>
            </div>
            <div class="row mb-3">
                <label for="" class="col-sm-4 col-form-label text-end">District<span class="required">*</span></label>
                <div class="col-sm-8">
                    <select class="form-select" asp-for="DistrictID" asp-items="@SuperCompanyDropdownBinder.District(Model.StateID)">
                        <option value="">--Select--</option>
                    </select>
                    <span asp-validation-for="DistrictID" class="text-danger"></span>
                </div>
            </div>
            <div class="row mb-3">
                <label for="" class="col-sm-4 col-form-label text-end">Taluka<span class="required">*</span></label>
                <div class="col-sm-8">
                    <select class="form-select" asp-for="TalukaID" asp-items="@SuperCompanyDropdownBinder.City(Model.DistrictID)">
                        <option value="">--Select--</option>
                    </select>
                    <span asp-validation-for="TalukaID" class="text-danger"></span>
                </div>
            </div>
            <div class="row mb-3">
                <label for="" class="col-sm-4 col-form-label text-end">City<span class="required">*</span></label>
                <div class="col-sm-8">
                    <select class="form-select" asp-for="CityID" asp-items="@SuperCompanyDropdownBinder.City(Model.StateID)">
                        <option value="">--Select--</option>
                    </select>
                    <span asp-validation-for="CityID" class="text-danger"></span>
                </div>
            </div>
            <div class="row mb-3">
                <label for="roleName" class="col-sm-4 col-form-label text-end">Area Name<span class="required">*</span></label>
                <div class="col-sm-8">
                    <input type="text" required="" class="form-control" asp-for="AreaOfficeName" maxlength="150">
                    <span asp-validation-for="AreaOfficeName" class="text-danger"></span>
                </div>
            </div>
            <div class="row mb-3">
                <label for="roleName" class="col-sm-4 col-form-label text-end">Zipcode<span class="required">*</span></label>
                <div class="col-sm-8">
                    <input type="text" required="" class="form-control" asp-for="ZIPCode" maxlength="10">
                    <span asp-validation-for="ZIPCode" class="text-danger"></span>
                </div>
            </div>
            <div class="modal-footer-sticky">
                <button class="btn btn-primary btn-info px-5 ladda-button" id="btnSave" type="button" onclick="fnSubmit()">
                    Save
                </button>
                <button type="button" data-bs-dismiss="offcanvas" class="btn btn-primary btn-info px-5">Cancel</button>
            </div>
        </div>
    </div>
</form>



<script type="text/javascript">
    function fnSubmit() {
        if ($("#frmzipcode").valid()) {
            var l = laddaStart('btnSave');
            modeldata = $("#frmzipcode").serialize();
            $.ajax({
                type: 'POST',
                url: '../SuperAdmin/Zipcode/Save',
                data: modeldata,
                dataType: 'json',
                beforeSend: function () { },
                success: function (data) {
                    console.log(data.status);
                    if (data.status) {
                        //notification
                        $("#canvas_zip").hide();//('hide');
                        Lobibox.notify('success', {
                            pauseDelayOnHover: true,
                            size: 'mini',
                            icon: 'bx bx-check-circle',
                            continueDelayOnInactiveTab: false,
                            position: 'bottom right',
                            msg: data.message
                        });
                    }
                    else {
                        Lobibox.notify('error', {
                            pauseDelayOnHover: true,
                            size: 'mini',
                            icon: 'bx bx-check-circle',
                            continueDelayOnInactiveTab: false,
                            position: 'bottom right',
                            msg: data.message
                        });
                    }
                },
                error: function (error) {
                    laddaStop(l);
                    Lobibox.notify('error', {
                        pauseDelayOnHover: true,
                        size: 'mini',
                        icon: 'bx bx-check-circle',
                        continueDelayOnInactiveTab: false,
                        position: 'bottom right',
                        msg: "@MessageHelper.Error"
                    });
                }
            }).always(function () {
                hideLoader();
            });
        }
    };
    var urlstate = '@Url.Action("GetState", "Base")';
    var urldistrict = '@Url.Action("GetDistrict", "Base")';
    var urltaluka = '@Url.Action("GetTaluka", "Base")';
    var urlcity = '@Url.Action("GetCity", "Base")';
    $(document).ready(function () {
        $("#CountryID").change(function () {
            $("#StateID").empty();
            $("#DistrictID").empty();
            $.ajax({
                type: 'POST',
                url: urlstate,
                dataType: 'json',
                data: { countryId: $("#CountryID").val() },
                success: function (response) {
                    $("#StateID").append('<option value>--Select--</option>');
                    $("#DistrictID").append('<option value>--Select--</option>');
                    if (response.status) {
                        console.log(response.data);
                        $.each(response.data, function (i, state) {
                            $("#StateID").append('<option value="'
                                + state.value + '">'
                                + state.text + '</option>');
                        });
                    }

                },
                error: function (ex) {
                    Lobibox.notify('error', {
                        pauseDelayOnHover: true,
                        size: 'mini',
                        icon: 'bx bx-check-circle',
                        continueDelayOnInactiveTab: false,
                        position: 'bottom right',
                        msg: "@MessageHelper.Error"
                    });
                }
            });
            return false;
        })
        $("#StateID").change(function () {
            $("#DistrictID").empty();
            $.ajax({
                type: 'POST',
                url: urldistrict,
                dataType: 'json',
                data: { stateId: $("#StateID").val() },
                success: function (response) {
                    $("#DistrictID").append('<option value>--Select--</option>');
                    if (response.status) {
                        console.log(response.data);
                        $.each(response.data, function (i, district) {
                            $("#DistrictID").append('<option value="'
                                + district.value + '">'
                                + district.text + '</option>');
                        });
                    }
                    
                },
                error: function (ex) {
                    Lobibox.notify('error', {
                        pauseDelayOnHover: true,
                        size: 'mini',
                        icon: 'bx bx-check-circle',
                        continueDelayOnInactiveTab: false,
                        position: 'bottom right',
                        msg: "@MessageHelper.Error"
                    });
                }
            });

            $("#CityID").empty();
            $.ajax({
                type: 'POST',
                url: urlcity,
                dataType: 'json',
                data: { stateId: $("#StateID").val() },
                success: function (response) {
                    $("#CityID").append('<option value>--Select--</option>');
                    if (response.status) {
                        console.log(response.data);
                        $.each(response.data, function (i, city) {
                            $("#CityID").append('<option value="'
                                + city.value + '">'
                                + city.text + '</option>');
                        });
                    }
                },
                error: function (ex) {
                    Lobibox.notify('error', {
                        pauseDelayOnHover: true,
                        size: 'mini',
                        icon: 'bx bx-check-circle',
                        continueDelayOnInactiveTab: false,
                        position: 'bottom right',
                        msg: "@MessageHelper.Error"
                    });
                }
            });
            return false;
        })
       
        $("#DistrictID").change(function () {
            $("#TalukaID").empty();
            $.ajax({
                type: 'POST',
                url: urltaluka,
                dataType: 'json',
                data: { districtID: $("#DistrictID").val() },
                success: function (response) {
                    $("#TalukaID").append('<option value>--Select--</option>');
                    
                    if (response.status) {
                        console.log(response.data);
                        $.each(response.data, function (i, taluka) {
                            $("#TalukaID").append('<option value="'
                                + taluka.value + '">'
                                + taluka.text + '</option>');
                        });
                    }

                },
                error: function (ex) {
                    Lobibox.notify('error', {
                        pauseDelayOnHover: true,
                        size: 'mini',
                        icon: 'bx bx-check-circle',
                        continueDelayOnInactiveTab: false,
                        position: 'bottom right',
                        msg: "@MessageHelper.Error"
                    });
                }
            });
            return false;
        })
    });
    
</script>

@await Html.PartialAsync("_ValidationScriptsPartial")